#!/bin/bash
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=1
#PBS -r n
#PBS -q @hades
#PBS -W depend=afterany:TOKEN
#PBS -o run.pbs.o$PBS_JOBID
#PBS -j oe
 
module load CUDA
cd $HOME/ift6266h16/projects/cat_dog
NAME=$PBS_JOBID
RESULT_PATH=./result/$NAME

THEANO_FLAGS="device=gpu,floatX=float32,nvcc.fastmath=True,compiledir=$RAMDISK" python run.py TOKEN > $RESULT_PATH.out.kaggle 2> $RESULT_PATH.err.kaggle
